create extension if not exists "pgcrypto";
create type public.app_role as enum ('worker', 'superadmin', 'client');
create type public.project_status as enum ('planning', 'active', 'review', 'complete');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', role public.app_role not null default 'client', organization text, avatar_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.projects (id uuid primary key default gen_random_uuid(), name text not null, description text not null default '', status public.project_status not null default 'planning', client_id uuid references public.profiles(id), owner_id uuid references public.profiles(id), due_date date, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.project_members (project_id uuid references public.projects(id) on delete cascade, user_id uuid references public.profiles(id) on delete cascade, primary key (project_id, user_id));
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, title text not null, body text not null, read_at timestamptz, created_at timestamptz not null default now());
create table public.audit_log (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());
alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_log enable row level security;
create or replace function public.current_role() returns public.app_role language sql stable security definer set search_path = public as $$ select role from public.profiles where id = auth.uid() $$;
create policy "profiles self or admin" on public.profiles for select using (id = auth.uid() or public.current_role() = 'superadmin');
create policy "projects visible to members" on public.projects for select using (owner_id = auth.uid() or client_id = auth.uid() or exists (select 1 from public.project_members m where m.project_id = id and m.user_id = auth.uid()) or public.current_role() = 'superadmin');
create policy "workers manage projects" on public.projects for all using (public.current_role() in ('worker','superadmin')) with check (public.current_role() in ('worker','superadmin'));
create policy "memberships visible to members" on public.project_members for select using (user_id = auth.uid() or public.current_role() = 'superadmin');
create policy "own notifications" on public.notifications for select using (user_id = auth.uid());
create policy "own notifications update" on public.notifications for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "audit admins only" on public.audit_log for select using (public.current_role() = 'superadmin');
insert into storage.buckets (id, name, public) values ('project-assets', 'project-assets', false) on conflict (id) do nothing;
create policy "project assets authenticated read" on storage.objects for select to authenticated using (bucket_id = 'project-assets');
create policy "project assets authenticated upload" on storage.objects for insert to authenticated with check (bucket_id = 'project-assets');
